### ISSUE TITLE
follow-up on issue 189: Crash at startup with recent GTK... still the same

### ISSUE THREAD

**Issue by GoogleCodeExporter** [freetuxtv/freetuxtv#193] opened 2016-01-19 15:22 UTC
```
Please complete the following information about your configuration:
- FreetuxTV version:
svn 750-1
- Linux distribution and version:
Arch Linux
- VLC version:
VLC media player 2.1.5 Rincewind (revision 2.1.4-49-gdab6cb5)
- ISP:
Orange

Describe here your problem:

After loading the channels on splash screen the program crashes. Symptoms are 
identical to issue 189:

What is the expected output? What do you see instead?

[FreetuxTV]    INFO       : Loading GtkBuilder object "dialogaddgroup" from 
/usr/local/share/freetuxtv/ui/addchannelsgroups.glade

** (freetuxtv:978): CRITICAL **: gtk_builder_window_get_top_window: assertion 
'GTK_IS_WINDOW(pObject)' failed

(freetuxtv:978): Gtk-CRITICAL **: gtk_window_set_transient_for: assertion 
'GTK_IS_WINDOW (window)' failed

(freetuxtv:978): Gtk-CRITICAL **: gtk_window_set_position: assertion 
'GTK_IS_WINDOW (window)' failed

(freetuxtv:978): Gtk-CRITICAL **: gtk_tree_view_get_selection: assertion 
'GTK_IS_TREE_VIEW (tree_view)' failed

(freetuxtv:978): Gtk-CRITICAL **: gtk_tree_selection_set_mode: assertion 
'GTK_IS_TREE_SELECTION (selection)' failed

(freetuxtv:978): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:978): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 
'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:978): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:978): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 
'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:978): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:978): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 
'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:978): Gtk-CRITICAL **: gtk_tree_store_clear: assertion 
'GTK_IS_TREE_STORE (tree_store)' failed
Segmentation fault (core dumped)




```

Original issue reported on code.google.com by `daniel.p...@free.fr` on 26 Jan 2015 at 6:45

**Comment by SaiyanRiku** [comment] 2016-06-09 12:16
Closed as duplicate of #189

**Closed by SaiyanRiku** 2016-06-09 12:16 UTC
Labels: auto-migrated
